// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


console.log("Hello, BuckleScript and Reason!");

var worker = new Worker("worker.js");

var msg = {
  text: "Hello world"
};

worker.postMessage(msg);

function msgBackHandler(name) {
  console.log("msgBackHandler");
  console.log(name);
  return /* () */0;
}

worker.onmessage = msgBackHandler;

exports.worker         = worker;
exports.msg            = msg;
exports.msgBackHandler = msgBackHandler;
/*  Not a pure module */
