// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


onmessage = function(e) {
  console.log("message received " + String(e));
  postMessage("my result");
  return /* () */0;
}

exports.onmessage = onmessage;
/* No side effect */
