// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("bs-jest/src/jest.js");

describe("create_webworkers", (function () {
        return Jest.test("to work", (function () {
                      var worker = new Worker("script.js");
                      return Jest.ExpectJs[/* toEqual */12]("script.js")(Jest.ExpectJs[/* expect */0](worker.url));
                    }));
      }));

/*  Not a pure module */
